 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HMS;

import java.sql.*;
import javax.swing.*;
/**
 *
 * @author mohsi
 */
public class StaffLogin extends javax.swing.JFrame {
    public int dcid,lab_ass_id;
    /**
     * Creates new form patientLogin
     */
    hmsDB database;
    public StaffLogin() {
        initComponents();
        database=new hmsDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        signin = new javax.swing.JButton();
        inputPass = new javax.swing.JPasswordField();
        dropDown = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Staff Login Form");

        jLabel2.setText("Enter User name :");

        jLabel3.setText("Enter Password:");

        signin.setText("Sigin");
        signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signinActionPerformed(evt);
            }
        });

        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctor", "Nurse", "Pharmacist", "Lab Assistant", "Receptionist", "Admin" }));
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signin)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dropDown, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(inputPass, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(inputPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(signin)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dropDownActionPerformed

    private void signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinActionPerformed
        // TODO add your handling code here:
        
        String query=null,user=null,pass=null;
        Statement stm=null;
        ResultSet myRs=null;
        String inputvar0,inputvar1;
        inputvar0=inputUsername.getText();
        inputvar1=inputPass.getText();
        boolean isFind=true;
        String tabelName=dropDown.getSelectedItem().toString();
        stm=database.getStatment();
       
            try{
                 if(tabelName == "Admin"){
         //        3- Execute Query
                     query="select * from admin";
         //                System.out.println("In try");
                         myRs=stm.executeQuery(query);
         //                System.out.println(myRs);
                            while(myRs.next()){
         //                       System.out.println(myRs.getString("username")+","+myRs.getString("password"));
                                user=myRs.getString("username");
                                pass=myRs.getString("password");
         //                       System.out.println("Loop");
                            }
                            database.myConn.close();
                            // Authenticating user(admin)
                            if (user.equals(inputvar0)&& pass.equals(inputvar1)){
                                System.out.println("Succees");
                                new adminOptions().setVisible(true);
                            }
                            else{

                                JOptionPane.showMessageDialog(StaffLogin.this,"Incorrect Username or Password..");  

                            }
                       }
                              //--------if doctor---------//
                 else if(tabelName =="Doctor"){
                     query="select doctorID,username,password from doctor";
        
                         myRs=stm.executeQuery(query);
                         
                            while(myRs.next()){
                                
                                user=myRs.getString("username");
                                pass=myRs.getString("password");
                                dcid=myRs.getInt("doctorID");
                            if (user.equals(inputvar0)&& pass.equals(inputvar1)){
                                System.out.print(dcid);
                                new DoctorUseCases(dcid).setVisible(true);
                                isFind=false;                                    
                                break;   
                           }   
                            
                            isFind=true;
                                }
                            //------- Dailouge box for incorrect------//
                             if (isFind){
                                JOptionPane.showMessageDialog(StaffLogin.this,"Incorrect Username or Password..");  
                            }
                 }
                   
                 //------------ If Lab Assistant---------------//
                 else if("Lab Assistant".equals(tabelName)){
                     query="select labAssistantID,username,password from labassistant";
        
                         myRs=stm.executeQuery(query);
                         
                            while(myRs.next()){
                                
                                user=myRs.getString("username");
                                pass=myRs.getString("password");
                                lab_ass_id=myRs.getInt("labAssistantID");
                            if (user.equals(inputvar0)&& pass.equals(inputvar1)){
//                                System.out.print(dcid);
                                new labAssistanPatient(lab_ass_id).setVisible(true);
                                isFind=false;                                    
                                break;   
                           }  
                            isFind=true;
                                }
                            //------- Dailouge box for incorrect------//
                             if (isFind){
                                JOptionPane.showMessageDialog(StaffLogin.this,"Incorrect Username or Password..");  
                            }
                 }
                 
                 
                 //--------------- For Pharmacist----------//
                 else if("Pharmacist".equals(tabelName)){
                     query="select username,password from pharmacist";
        
                         myRs=stm.executeQuery(query);
                         
                            while(myRs.next()){
                                
                                user=myRs.getString("username");
                                pass=myRs.getString("password");
                                
                            if (user.equals(inputvar0)&& pass.equals(inputvar1)){
//                                System.out.print(dcid);
                                new pharmacistUseCase().setVisible(true);
                                isFind=false;                                    
                                break;   
                           }  
                            isFind=true;
                                }
                            //------- Dailouge box for incorrect------//
                             if (isFind){
                                JOptionPane.showMessageDialog(StaffLogin.this,"Incorrect Username or Password..");  
                            }
                 }
                 
                 //------------------ For Nurse--------------------///
                 
                 else if("Nurse".equals(tabelName)){
                     query="select username,password from nurse";
        
                         myRs=stm.executeQuery(query);
                         
                            while(myRs.next()){
                                
                                user=myRs.getString("username");
                                pass=myRs.getString("password");
                                
                            if (user.equals(inputvar0)&& pass.equals(inputvar1)){
//                                System.out.print(dcid);
                                new nurseUseCase().setVisible(true);
                                isFind=false;                                    
                                break;   
                           }  
                            isFind=true;
                                }
                            //------- Dailouge box for incorrect------//
                             if (isFind){
                                JOptionPane.showMessageDialog(StaffLogin.this,"Incorrect Username or Password..");  
                            }
                 }
            }
            catch(Exception e){
                
                JOptionPane.showMessageDialog(StaffLogin.this,e);  
            }
        
    }//GEN-LAST:event_signinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JPasswordField inputPass;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton signin;
    // End of variables declaration//GEN-END:variables
}
